# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [4]:
import numpy as np
b = np.zeros(100)
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2.Создать вектор размера 100, заполненный единицами

In [8]:
a = np.ones(100)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3.Создать вектор размера 100, заполненный числом 3

In [7]:
a = np.full(100, 3)
a

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [90]:
help (np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

#### 5. Поменять 2 строки в матрице

In [27]:
a = np.arange(9).reshape(3, 3)
a[[0, 1]] = a[[1, 0]]
a

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

#### 6. Создать вектор со значениями от 10 до 100

In [30]:
a = np.arange(10, 101)
a

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### 7. Развернуть вектор (первый становится последним)

In [53]:
a = np.arange(10)
a = a[::-1]
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [42]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [65]:
a = np.arange(1, 6)
c = 3
b = np.zeros(len(a) + (len(a) - 1) * c)
b[::c + 1] = a
b

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 10. Создать 3x3 единичную матрицу

In [67]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Создать массив 3x3x3 со случайными значениями

In [69]:
a = np.random.random((3, 3, 3))
a

array([[[0.49557306, 0.31339051, 0.7584448 ],
        [0.87499521, 0.77223933, 0.03292842],
        [0.28803069, 0.93975346, 0.62501553]],

       [[0.7292562 , 0.72641221, 0.90121208],
        [0.30943916, 0.97527826, 0.79694991],
        [0.29813516, 0.89327348, 0.90340317]],

       [[0.13571823, 0.71734439, 0.88441848],
        [0.90960709, 0.35959754, 0.93274307],
        [0.83989673, 0.29270018, 0.68589199]]])

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [76]:
a = np.random.random((10, 10))
minA = a.min()
maxA = a.max()
a, minA, maxA

(array([[0.34642295, 0.15734623, 0.53884662, 0.05096119, 0.89119511,
         0.37773258, 0.19538812, 0.91541595, 0.08337281, 0.11435099],
        [0.80027194, 0.39196313, 0.59775345, 0.45345376, 0.76666977,
         0.9853694 , 0.54697331, 0.65802429, 0.50250006, 0.62971461],
        [0.14068766, 0.58901295, 0.57309468, 0.42503951, 0.74425471,
         0.28704831, 0.10009492, 0.2788894 , 0.64444948, 0.04080679],
        [0.74912787, 0.73326241, 0.84585845, 0.95077497, 0.55919161,
         0.49215342, 0.60166717, 0.22273745, 0.00750642, 0.05601049],
        [0.09763837, 0.32724335, 0.44840753, 0.34816658, 0.05724755,
         0.7887349 , 0.49464154, 0.34923077, 0.4816261 , 0.87321466],
        [0.75520619, 0.89770177, 0.55175225, 0.74279067, 0.69713807,
         0.40983038, 0.08256597, 0.04281086, 0.62461976, 0.23118907],
        [0.96550523, 0.32176373, 0.67240136, 0.56423987, 0.0395946 ,
         0.37239818, 0.43967504, 0.90720114, 0.21281328, 0.07148851],
        [0.77249632, 0.4849

#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [79]:
a = np.random.random(30)
b = a.mean()
a, b

(array([0.43395524, 0.71322721, 0.23478088, 0.79032798, 0.00351147,
        0.21674163, 0.21858826, 0.26736065, 0.90088559, 0.4883216 ,
        0.81404015, 0.7680709 , 0.41023349, 0.49025067, 0.26543198,
        0.40830371, 0.88920175, 0.13030474, 0.87919477, 0.4812465 ,
        0.41130908, 0.87412714, 0.91831805, 0.53945128, 0.10933218,
        0.5786231 , 0.58089353, 0.22306772, 0.82639919, 0.79429251]),
 0.5219930997345893)

#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [90]:
a = np.ones((5, 5))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

In [66]:
# поворот массива на 90 градусов 
a = np.array([[1, 4, 2], [1, 0, 8], [0, 7, 1]])
print(a)
print(np.rot90(a))

[[1 4 2]
 [1 0 8]
 [0 7 1]]
[[2 8 1]
 [4 0 7]
 [1 1 0]]


#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [94]:
a = np.diag(np.array([1, 2, 2, 3, 4]))
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [102]:
a = np.zeros((8, 8))
a[1::2, ::2] = 1
a[::2, 1::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [118]:
a = np.unravel_index(100, (6, 7, 8))
a

(1, 5, 4)

#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [111]:
a = np.array([[0,1],[1,0]])
repetitions = (4, 4)
a = np.tile(a, repetitions)
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Перемножить матрицы 5x3 и 3x2

In [119]:
a = np.ones((5, 3))
b = np.ones((3, 2))
res = np.dot(a, b)
res

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [144]:
a = np.arange(10)
a[(3 < a) & (a < 8)] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [127]:
a = np.arange(5)
rep = (5, 1)
print(np.tile(a, rep))

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 24. Есть генератор, сделать с его помощью массив

In [87]:
def generate():
    for x in range(10):
        yield x
a = np.fromiter(generate(), dtype = float, count = -1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [154]:
np.linspace(0, 1, 10, False)[1:]

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### 26. Отсортировать вектор

In [165]:
a = np.random.random(10)
a.sort()
a

array([0.13803204, 0.20932621, 0.26224128, 0.26767351, 0.33797347,
       0.51119449, 0.56961529, 0.62265504, 0.71552532, 0.9889927 ])

#### 27. Проверить, одинаковы ли 2 numpy массива

In [169]:
a = np.arange(5)
b = np.arange(6)
res = np.array_equal(a ,b)
res

False

#### 28. Сделать массив неизменяемым

In [93]:
a = np.arange(10)
a.flags.writeable = False
a[2] = 5
a

ValueError: assignment destination is read-only

#### 29. Найти n наибольших значений в массиве

In [175]:
a = np.arange(100)
np.random.shuffle(a)
n = 5
print (a[np.argpartition(-a,n)[:n]])

[98 99 97 96 95]


#### 30. Заменить максимальный элемент на ноль

In [180]:
a = np.arange(20)
a[a.max()] = 0 
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18,  0])

#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [61]:
a = np.zeros([5, 5], [('x', float), ('y', float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
a

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [63]:
a = np.arange(8)
b = a + 0.5
c = 1 / np.subtract.outer(a,b)
print(np.linalg.det(c))

3638.1636371179666


#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [67]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 34. Напечатать все значения в массиве

In [198]:
np.set_printoptions(threshold=5)
print(np.arange(100))

[ 0  1  2 ... 97 98 99]


#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [73]:
a = np.arange(100)
b = np.random.uniform(0, 100)
i = (np.abs(a-b)).argmin()
a[i], a, b

(30, array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]), 30.159753981119476)

#### 36. Преобразовать массив из float в int

In [69]:
a = np.arange(10)
a = a.astype(np.float32)
a.dtype

dtype('float32')

#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [13]:
a = np.array([[4, 5], [6, 7]])
for i, x in np.ndenumerate(a):
    print(i, x)

(0, 0) 4
(0, 1) 5
(1, 0) 6
(1, 1) 7


#### 38. Случайно расположить p элементов в 2D массив

In [46]:
p = 3
a = np.random.randint(3, 10, (2, 3))
print(a)
np.put(a, np.random.choice(range(a.size), p), 0)
a

[[9 4 9]
 [8 5 7]]


array([[9, 0, 0],
       [0, 5, 7]])

#### 39. Отнять среднее из каждой строки в матрице

In [30]:
a = np.random.randint(1, 10, (3, 4))
m = a.mean(axis = 1, keepdims = True)
k = a - m
a, k, m

(array([[4, 3, 2, 6],
        [7, 7, 4, 2],
        [4, 3, 1, 3]]), array([[ 0.25, -0.75, -1.75,  2.25],
        [ 2.  ,  2.  , -1.  , -3.  ],
        [ 1.25,  0.25, -1.75,  0.25]]), array([[3.75],
        [5.  ],
        [2.75]]))

#### 40. Отсортировать матрицу по n-ому столбцу

In [204]:
Z = np.random.randint(0,10,(3,3))
n = 1  # Нумерация с нуля
print(Z)
print(Z[Z[:,n].argsort()])

[[5 9 4]
 [8 5 3]
 [6 2 9]]
[[6 2 9]
 [8 5 3]
 [5 9 4]]


#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [33]:
a = np.random.randint(1, 10, (3, 4))
res = (~a.any(axis = 0)).any()
a, res


(array([[5, 7, 8, 1],
        [2, 4, 2, 4],
        [6, 3, 1, 9]]), False)

#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [60]:
a = np.ones(10)
print(a)
b = np.random.randint(0, a.size, 20)
print(b)
a += np.bincount(b, minlength=len(a))
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[4 7 4 7 8 7 2 7 7 3 7 6 0 8 8 0 3 4 3 2]
[3. 1. 3. 4. 4. 1. 2. 7. 4. 1.]


#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [83]:
w, h = 16, 16
a = np.random.randint(0, 2, (h, w, 3)).astype(np.ubyte)
b = a[...,0] * 256 * 256 + a[...,1] * 256 + a[...,2]
n = len(np.unique(b))
print(np.unique(a))

[0 1]


#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [80]:
a = np.random.randint(0, 10, (2, 2, 2, 3))
sum = a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)
a

[[37 20]
 [19 36]]


array([[[[3, 9, 3],
         [8, 8, 6]],

        [[4, 3, 3],
         [0, 7, 3]]],


       [[[0, 8, 4],
         [3, 2, 2]],

        [[5, 4, 9],
         [7, 3, 8]]]])