# Системы линейных уравнений. 

## Практическое задание

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

__РЕШЕНИЕ__

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4\\
\end{matrix}
\end{pmatrix}\Leftrightarrow \begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & -1 & 1 & 5\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4\\
\end{matrix}
\end{pmatrix}\Leftrightarrow \begin{pmatrix}
\left.\begin{matrix}
1 & 0 & 0 & 3\\ 
0 & 1 & 0 & -6.5\\ 
0 & 0 & 1 & -1.5
\end{matrix}\right|
\begin{matrix}
-2\\ 
0\\
-2\\
\end{matrix}
\end{pmatrix}\Leftrightarrow\begin{cases}
x_{1}=-2-3x_4 \\
x_{2}=6.5x_4 \\
x_{3}=1.5x_4-2
\end{cases}$$

СЛАУ имеет бесконечное кол-во решение указанного вида

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}\leftrightarrow\begin{cases}
x_{1}=1, \\
x_{3}=3, \\
x_{2}=2;
\end{cases}$

СЛАУ совместимая с одним решением

$$\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1 \\ 
2 & -5 & -3\\ 
1 & 1 & -1 
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
0\\
\end{matrix}
\end{pmatrix} \Leftrightarrow \begin{pmatrix}
\left.\begin{matrix}
0 & -4 & 4 \\ 
0 & -7 & -1 \\ 
1 & 1 & -1
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
0\\
\end{matrix}
\end{pmatrix}\Leftrightarrow \begin{pmatrix}
\left.\begin{matrix}
0 & 1 & 0\\ 
0 & 0 & 1\\ 
1 & 0 & 0
\end{matrix}\right|
\begin{matrix}
2\\ 
3\\
1\\
\end{matrix}
\end{pmatrix}\Leftrightarrow\begin{cases}
x_{1}=1 \\
x_{2}=2\\
x_{3}=3
\end{cases}$$

In [3]:
import numpy as np

In [5]:
A = np.array([[3,-1,-1],[2,-5, -3],[1,1,-1]])
print("Ранг матрицы коэфициентов:", np.linalg.matrix_rank(A))
A_ = np.array([[3,-1,-1,4],[2,-5, -3,-17],[1,1,-1,0]])
print("Ранг расширенной матрицы:", np.linalg.matrix_rank(A_))

Ранг матрицы коэфициентов: 3
Ранг расширенной матрицы: 3


б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}\leftrightarrow \begin{cases}
0=5, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
0=11;
\end{cases}$

СЛАУ несовместимая и не имеет решений

In [20]:
import numpy as np
A = np.array([[2,-4,-6],[1,-2,3],[3,-6,9]])
print("Ранг матрицы коэфициентов:", np.linalg.matrix_rank(A))
A_ = np.array([[2,-4,-6,1],[1,-2,3,-2],[3,-6,9,5]])
print("Ранг расширенной матрицы:", np.linalg.matrix_rank(A_))

Ранг матрицы коэфициентов: 2
Ранг расширенной матрицы: 3


в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases} \leftrightarrow\begin{cases}
5x_{1} = 21x_3 - 8, \\
5x_{2} = 14 - 23x_3 
\end{cases}$

СЛАУ совместимая с бесконечным кол-вом решений

In [7]:
A = np.array([[1,2,5],[3,1,-8]])
print("Ранг матрицы коэфициентов:", np.linalg.matrix_rank(A))
A_ = np.array([[1,2,5,4],[3,1,-8,-2]])
print("Ранг расширенной матрицы:", np.linalg.matrix_rank(A_))

Ранг матрицы коэфициентов: 2
Ранг расширенной матрицы: 2


__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$


In [8]:
import numpy as np
A = np.array([[1,3,-2,4],[0,5,0,1],[0,0,3,0],[0,0,0,2]])

A_ = np.array([[1,3,-2,4,3],[0,5,0,1,2],[0,0,3,0,4],[0,0,0,2,1]])

print("Ранг матрицы коэфициентов:", np.linalg.matrix_rank(A))
print("Ранг расширенной матрицы:", np.linalg.matrix_rank(A_))
print("Согласно Теореме Кронекера — Капелли система совместима и имеет одно решение так как ранг матрицы коэфициентов и расширеной матрицы совпадают и равны числу неизвестных")

Ранг матрицы коэфициентов: 4
Ранг расширенной матрицы: 4
Согласно Теореме Кронекера — Капелли система совместима и имеет одно решение так как ранг матрицы коэфициентов и расширеной матрицы совпадают и равны числу неизвестных


__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

В случае если равенство

$c = 2b - a$

не выполняется, система является не совместной

__5.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

Найдем определитель матрицы коэффициентов:
$$detA=\begin{vmatrix}
1 & -2 \\ 
3 & -4
\end{vmatrix}=(1 \cdot (-4))-(-2\cdot 3)=2$$

следовательно, система совместна.


Найдем определители $detA_{1}$, $detA_{2}$:

$$detA_{1}=\begin{vmatrix}
1 & -2\\ 
7 & -4 
\end{vmatrix}= (1 \cdot (-4))-(-2\cdot 7)=10$$

$$detA_{2}=\begin{vmatrix}
1 & 1 \\ 
3 & 7
\end{vmatrix}=7-3=4$$

Найдем решение по формулам Крамера:

$$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2}=5,$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2}=2,$$

Проверим

In [9]:
A = np.array([[1,-2],[3,-4]])
A1 = np.array([[1,-2],[7,-4]])
A2 = np.array([[1,1],[3,7]])
print(f'х1 = {np.linalg.det(A1)/np.linalg.det(A):.0f}')
print(f'х2 = {np.linalg.det(A2)/np.linalg.det(A):.0f}')

х1 = 5
х2 = 2


 __6.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

  $$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

$$L = \begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$$

In [33]:

# LU decomposition
from numpy import array
from scipy.linalg import lu
# define a square matrix
A = array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
print(A)
# LU decomposition
P, L, U = lu(A)
print(P)
print(L)
print(U)
# reconstruct
B = P.dot(L).dot(U)
print(B)

[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[1.   0.   0.  ]
 [0.67 1.   0.  ]
 [0.33 0.8  1.  ]]
[[ 3.   26.   30.  ]
 [ 0.   -8.33 -8.  ]
 [ 0.    0.    0.4 ]]
[[ 1.  2.  4.]
 [ 2.  9. 12.]
 [ 3. 26. 30.]]


__7.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

Матрица коэффициентов $A$ будет иметь вид

$$\begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix}$$

Начнем прямой ход метода Гаусса.
Матрица коэффициентов будет иметь вид
$$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & \frac{-23}{2}\\
0 & 0 & \frac{52}{3}
\end{pmatrix}$$

а матрица $L$ —

$$\begin{pmatrix}
1 & 0 & 0 \\ 
\frac{11}{2} & 1 & 0 \\ 
\frac{9}{2} & \frac{7}{2} & 1
\end{pmatrix}.$$

Решим теперь систему $Ly=b:$

$$\begin{cases}
y_{1}=1, \\
\frac{11}{2}y_{1}+y_{2}=-6, \\
\frac{9}{2}y_{1}+ \frac{7}{2}y_{2}+y_{3}=-5.
\end{cases}$$

$$y_{1} = 1,$$

$$y_{2}=-6 -\frac{11}{2} =11.5$$

$$y_{3}=-5-\frac{9}{2} - \frac{7}{2}=-13.$$

И затем систему

$$x_1 = -1$$

Произведем проверку, подставив полученные значения переменных в исходную систему:
$$\begin{cases}
2(-1)+3=1 \\
11(-1)+5=-6 \\
9(-1)+4=-5
\end{cases}$$

__8.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

Произведем разложение на $LL^{T}$:

$$l_{11}=\sqrt{a_{11}}=\sqrt{81} = 9,$$
$$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9} = -5,$$
$$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9} = 5,$$

$$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 25} = 5,$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{12}l_{13} \right)=\frac{1}{5}\left ( -15 - (-5)\cdot 5 \right )=2,$$

$$l_{33}=\sqrt{a_{33}-l_{13}^{2}-l_{32}^{2}}=\sqrt{38-25-4}=\sqrt{9} = 3.$$

Получили матрицу 

$$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5\\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$$

Решим систему $Ly=b:$

$$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases}$$

$$y_{1} = 59,$$

$$y_{2}=\frac{5\cdot 59 - 460}{5} = -33,$$

$$y_{3}=\frac{193 - 5 \cdot 59 -2 \cdot (-33)}{3}=-12.$$

И решим систему $L^{T}x=y:$

$$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59, \\
5x_{2}+2x_{3}=-33, \\
3x_{3}=-12.
\end{cases}$$

$$x_{3}=-4,$$

$$x_{2}=\frac{-33+8}{5} = -5$$

$$x_{1}=\frac{59-25+20}{9}=6.$$

Осуществим проверку c помощью numpy

In [31]:
from numpy.linalg import cholesky

A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
print(A)

L = cholesky(A)
print(L)

B = L.dot(L.T)
print(B)

[[ 81 -45  45]
 [-45  50 -15]
 [ 45 -15  38]]
[[ 9.  0.  0.]
 [-5.  5.  0.]
 [ 5.  2.  3.]]
[[ 81. -45.  45.]
 [-45.  50. -15.]
 [ 45. -15.  38.]]


9. 1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [17]:
#Определим способ отображения чисел с плавающей запятой
np.set_printoptions(precision=2, suppress=True)

In [18]:
A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [19]:
U, s, W = np.linalg.svd(A)

# Транспонируем матрицу W
V = W.T

# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [20]:
print(f'Матрица D:\n{D}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [22]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]


In [24]:
# Убедимся, что она действительно ортогональна
print(np.dot(U.T, U))

[[ 1.  0. -0. -0. -0.]
 [ 0.  1.  0. -0.  0.]
 [-0.  0.  1. -0. -0.]
 [-0. -0. -0.  1. -0.]
 [-0.  0. -0. -0.  1.]]


In [26]:
print(f'Матрица V:\n{V}')

Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [28]:
# Убедимся, что она действительно ортогональна
print(np.dot(V.T, V))

[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]


In [30]:
# Проведем проверку
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1.  0.]]
