## Практическое задание

In [1]:
import numpy as np

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$; $AB$ и $BA$ - неопределены (недопустимая операция)
   
   
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$; $AB$ - неопределена; $BA$ - $2\times 3$
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$; $AB$ - $3\times 3$; $BA$ - $8\times 8$
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$. $AB$ - $4\times 4$; $BA$ - $4\times 4$

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$ 

In [18]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
ab= np.dot(a,b)
print(f'Матрица C = A + B\n{a + b}\n')
print(f'Матрица AB = A * B\n{ab}\n')

Матрица A
[[ 1 -2]
 [ 3  0]]

Матрица B
[[ 4 -1]
 [ 0  5]]

Матрица C = A + B
[[ 5 -3]
 [ 3  5]]

Матрица AB = A * B
[[  4 -11]
 [ 12  -3]]



__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [12]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2 ,-1]])
C = np.array([[2 ,-4],[1, 1]])
D = A*3+(-2)*B+4*C
print(f"Линейная комбинация  3𝐴 − 2𝐵 + 4𝐶 = \n{D}\n")

Линейная комбинация  3𝐴 − 2𝐵 + 4𝐶 = 
[[ 11  -5]
 [  9 -12]]



__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [20]:
A = np.array([[4, 1], [5, -2], [2, 3]])
At = A.T
print(f'Матрица A\n{A}\n')
print(f'Матрица A\n{At}\n')
AAt = np.dot(A, At)
print(f'Матрица AAt\n{AAt}\n')
AtA = np.dot(At, A)
print(f'Матрица AtA\n{AtA}\n')

Матрица A
[[ 4  1]
 [ 5 -2]
 [ 2  3]]

Матрица A
[[ 4  5  2]
 [ 1 -2  3]]

Матрица AAt
[[17 18 11]
 [18 29  4]
 [11  4 13]]

Матрица AtA
[[45  0]
 [ 0 14]]




__5.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

In [25]:
print('Определитель:sin^2(x)+cos^2(x) = 1')

Определитель:sin^2(x)+cos^2(x) = 1


   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

In [29]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Определитель:{np.linalg.det(a):.0f}')

Определитель:180


   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [31]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Определитель:
-0


определитель такой матрицы равен 0 т.к если из второй и третьей строки вычесть первую то вторая и третья строки будет линейно зависимыми

__6.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная(Определитель равен 0)

In [34]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Определитель:{np.linalg.det(a):.0f}')

Определитель:0


__7.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

In [35]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
r = np.linalg.matrix_rank(a)
print(f'Ранг матрицы: {r}')

Ранг матрицы: 2
